[env]
TERM = "xterm-256color"

[font]
size = 19

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
action = "ScrollLineUp"
key = "K"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollLineDown"
key = "J"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageUp"
key = "U"
mods = "Alt"

[[keyboard.bindings]]
action = "ScrollPageDown"
key = "D"
mods = "Alt"

[scrolling]
history = 5000

[window]
# title = "Alacritty"
opacity = 1.0

# [window.class]
# general = "Alacritty"
# instance = "Alacritty"

# [window.padding]
# x = 10
# y = 10


# other stuff
# window.opacity = 1.0
# Colors (Gruvbox Material Medium Light)

# Default colors
[colors.primary]
background = '#fbf1c7'
foreground = '#654735'

# Normal colors
[colors.normal]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#eee0b7'

# Bright colors (same as normal colors)
[colors.bright]
black   = '#654735'
red     = '#c14a4a'
green   = '#6c782e'
yellow  = '#b47109'
blue    = '#45707a'
magenta = '#945e80'
cyan    = '#4c7a5d'
white   = '#eee0b7'
