#!/bin/bash

LIGHT="/home/cardoso/.config/termite/themes/base16-gruvbox-light-soft.config"
DARK="/home/cardoso/.config/termite/themes/base16-gruvbox-dark-hard.config"
CONFIG_NO_COLOR="/home/cardoso/.config/termite/config_no_color"
CONFIG="/home/cardoso/.config/termite/config"
_TIME_=$(date +%H)

if [ $_TIME_ -ge 8 -a $_TIME_ -lt 18 ]; then
        redshift -P -O 4800 &
        cp $CONFIG_NO_COLOR $CONFIG
        cat $LIGHT >> $CONFIG
else
        redshift -P -O 3600 &
        cp $CONFIG_NO_COLOR $CONFIG
        cat $DARK >> $CONFIG
fi
