#!/bin/bash

# vol_level="$(amixer get Master | awk -F'[][]' 'END{ print $2 }') "
# is_mute=$(amixer get Master | awk ' /%/{print ($NF=="[off]" ? 1 : 0); exit;}')
# 
# echo $vol_level $is_mute
# if [ $is_mute = 1 ]
# then
#     echo "it is muted"
# fi
data=$(amixer -D pulse get Master)
# data=$(amixer -D pulse get Master | grep -o off)

mute=$(echo $data | grep -o off)
[ -n $mute ] && echo " 婢 "&& exit 1

level=$(echo $data |  grep -o -m 1 '[0-9]\+\%' )
echo "  $level " && exit 0
