#!/bin/bash

data=`acpi -b`
chr=`echo $data | awk '{ print $3 }'`

case $BLOCK_BUTTON in
    3)
        remain=$(echo $data | awk '{ print $5 }')
        [ $chr == 'Discharging,' ] \
            && notify-send "Discharging: $remain remaining"
        [ $chr == 'Charging,' ] \
            && notify-send "Charging: $remain remaining"
        ;;
esac

bat=`echo $data | grep -E -o '[0-9][0-9]?%'`


[ $chr == "Discharging," ] && echo "  $bat " || echo "  $bat "

# Set urgent flag below 5% and notify
[ ${bat%?} -le 10 ] && [ $chr == "Discharging," ] \
    && notify-send -u critical "  CHARGE BATTERY!" \
    && exit 33

[ ${bat%?} -le 10 ] && exit 33

[ ${bat%?} -ge 97 ] && notify-send -u critical "Battery fully charged!"

exit 0
