#!/bin/bash
case $BLOCK_BUTTON in
    3) notify-send "$(ps axch -o cmd:18,%cpu --sort=-%cpu | head)"
        ;;
esac

read cpu a b c previdle rest < /proc/stat
prevtotal=$((a+b+c+previdle))
sleep 0.5
read cpu a b c idle rest < /proc/stat
total=$((a+b+c+idle))
cpu=$((100*( (total-prevtotal) - (idle-previdle) ) / (total-prevtotal) ))

# temp=`sensors | grep temp1: | head -1 | awk -F' ' '{ print $2 }'`
temp=`sensors | grep "Core 0:" | head -1 | awk -F' ' '{ print $3 }'`
temp=`echo ${temp:1} | awk -F '.' '{ print $1}'`

load_=`cat /proc/loadavg | awk -F' ' '{ print $1}'`
load_bool=`echo $load_'>'4.5 | bc -l`

echo "  $cpu%   $temp°C   $load_ "

[ $cpu -ge 75 ]  || [ $load_bool -gt 0 ]  || [ $temp -ge 75 ] && exit 33

exit 0
