#!/bin/bash

case $BLOCK_BUTTON in
    3) notify-send "Most memory intensive processes:
        $(ps axch -o cmd:18,%mem --sort=-%mem | head -n 5)"
        ;;
esac

echo "  $(free -m | awk '/^Mem/ { print $3 "/" $2 MiB }') MiB "
