#!/bin/bash

case $BLOCK_BUTTON in
    3) notify-send "Most intensive memory processes:
        $(ps axch -o cmd:18,%mem --sort=-%mem | head)"
        ;;
esac

echo "  $(free -m | awk '/^Mem/ { print $3 "/" $2 MiB }') MiB "
