#!/bin/bash

HOME="/home/cardoso/"

# time of the day and changes of day and night
TIME=$(date +%H)
DAY=7
NIGHT=18

# redshift screen temperatures
DAY_TEMP=5100
NIGHT_TEMP=3500

# brightness percent
BRIGHT_DAY=18
BRIGHT_NIGHT=12

# Alacritty
ALACRITTY_CONFIG="${HOME}/.config/alacritty/alacritty.toml"
ALACRITTY_CONFIG_NO_COLOR="${HOME}/.config/alacritty/alacritty_no_color.toml"
ALACRITTY_LIGHT="/home/cardoso/dotfiles/alacritty/alacritty-theme/themes/gruvbox_material_medium_light.toml"
ALACRITTY_DARK="/home/cardoso/dotfiles/alacritty/alacritty-theme/themes/gruvbox_material_medium_dark.toml"

# Xresources
DARK_XRES="${HOME}/.config/xresources/gruvbox_material_dark"
LIGHT_XRES="${HOME}/.config/xresources/gruvbox_material_light"
# DARK_XRES="${HOME}/.config/xresources/solarized_dark"
# LIGHT_XRES="${HOME}/.config/xresources/solarized_light"
XRES="${HOME}/.Xresources"

# Zathura
ZAT_RC_NO_COLOR="${HOME}/.config/zathura/zathura_no_colorrc"
ZAT_RC="${HOME}/.config/zathura/zathurarc"
ZAT_DARK="${HOME}/.config/zathura/colors/solarized_darkrc"
ZAT_LIGHT="${HOME}/.config/zathura/colors/solarized_lightrc"
ZAT_DARK="${HOME}/.config/zathura/colors/gruvbox_material_darkrc"
ZAT_LIGHT="${HOME}/.config/zathura/colors/gruvbox_material_lightrc"

update_zathura(){
        cp $ZAT_RC_NO_COLOR $ZAT_RC
        cat $ZAT_COLOR >> $ZAT_RC
}

update_alacritty(){
        cp $ALACRITTY_CONFIG_NO_COLOR $ALACRITTY_CONFIG
        cat $ALACRITTY_COLOR >> $ALACRITTY_CONFIG
        # echo $ALACRITTY_COLOR >> $ALACRITTY_CONFIG
}

if [ $TIME -ge $DAY ] && [ $TIME -lt $NIGHT ]; then
        notify-send "Changing to Light Mode"

        # Alacritty
        ALACRITTY_COLOR=${ALACRITTY_LIGHT}
        # Xresources
        cat $LIGHT_XRES > $XRES
        # Zathura
        ZAT_COLOR=${ZAT_LIGHT}
        # xbacklight
        BRIGHT=${BRIGHT_DAY}
        # redshift
        TEMP=${DAY_TEMP}
        [ "$(pgrep -i redshift)" ] || redshift -P -O $DAY_TEMP &>/dev/null
else
        notify-send "Changing to Dark Mode"
        # Alacritty
        ALACRITTY_COLOR=${ALACRITTY_DARK}
        # Xresources
        cat $DARK_XRES > $XRES
        # Zathura
        ZAT_COLOR=${ZAT_DARK}
        # xbacklight
        BRIGHT=${BRIGHT_NIGHT}
        # redshift
        TEMP=${NIGHT_TEMP}
fi

# update colors
update_alacritty
update_zathura
xrdb -merge $XRES
xrdb $XRES
xbacklight -set $BRIGHT
[ "$(pgrep -i redshift)" ] || redshift -P -O $TEMP &>/dev/null

desktop=$(echo $DESKTOP_SESSION)
[ "$desktop" == "i3" ] ||  [ "$desktop" == "ubuntu" ]  || [ "$desktop" == "regolith" ] \
        && i3-msg reload &>/dev/null
exit 0
