#!/bin/bash

_TIME_=$(date +%H)

LIGHT="/home/cardoso/.config/termite/themes/base16-gruvbox-light-soft.config"
DARK="/home/cardoso/.config/termite/themes/base16-gruvbox-dark-hard.config"
CONFIG_NO_COLOR="/home/cardoso/.config/termite/config_no_color"
CONFIG="/home/cardoso/.config/termite/config"

DARK_XRES="/home/cardoso/.config/xresources/gruvbox_material_dark"
LIGHT_XRES="/home/cardoso/.config/xresources/gruvbox_material_light"
XRES="/home/cardoso/.Xresources"

if [ $_TIME_ -ge 8 -a $_TIME_ -lt 18 ]; then
        cp $CONFIG_NO_COLOR $CONFIG
        cat $LIGHT >> $CONFIG
        cat $LIGHT_XRES > $XRES
else
        cp $CONFIG_NO_COLOR $CONFIG
        cat $DARK >> $CONFIG
        cat $DARK_XRES > $XRES
fi

sleep 5
xrdb /home/cardoso/.Xresources

desktop=$(echo $DESKTOP_SESSION)
[ $desktop = "i3" ] && i3-msg reload && exit 0
