#!/bin/bash

[ "$NB" ] || NB="#282828"
[ "$NF" ] || NF="#d79921"
[ "$SB" ] || SB="#cc241d"
[ "$SF" ] || SF="#282828"
[ "$FN" ] || FN="Fira Code:pixelsize=18"

[ $1 == "dmenu" ]  && dmenu_run -nb "$NB" -nf "$NF" -sb "$SB" -sf "$SF" \
        -fn "$FN"

[ $1 == "j4" ] && j4-dmenu-desktop --dmenu="dmenu -i -nb '$NB' -nf '$NF' \
        -sb '$SB' -sf '$SF' -fn '$FN'"
