#!/bin/bash

host=$(hostname)

echo $FN
[ "$NB" ] || NB="#282828"
[ "$NF" ] || NF="#d79921"
[ "$SB" ] || SB="#cc241d"
[ "$SF" ] || SF="#282828"
[ "$FN" ] || FN="Fira Code:pixelsize=18"

options="HDMI_only\nLap_only\nManual"
operation=$(echo -e "$options" | dmenu -i -p "Action: " -nb $NB -nf $NF \
    -sb $SB -sf $SF -fn "$FN")


[ -z $operation ] && exit -1

case $operation in
    Manual )
        arandr & disown
        ;;
    HDMI_only )
        [ $host == 'cardosoarco' ] \
            && /home/cardoso/.config/scripts/screen_layouts/HDMI_only.sh \
            ; nitrogen --restore ; exit 0
        [ $host == 'kimura'] \
            && /home/cardoso/.config/scripts/screen_layouts/HDMI_only_mac.sh \
            ; setxkbmap latam ; nitrogen --restore ; exit 0
        ;;
    Lap_only )
        [ $host == 'cardosoarco' ] \
            && /home/cardoso/.config/scripts/screen_layouts/Lap_only.sh \
            ; nitrogen --restore ; exit 0
        [ $host == 'kimura'] \
            && /home/cardoso/.config/scripts/screen_layouts/HDMI_only_mac.sh \
            ; setxkbmap latam ; nitrogen --restore ; exit 0
        ;;
esac
