#!/bin/bash

txt="shutdown
suspend
reboot
hibernate
logout
lock"
operation=`echo "$txt" | rofi -dmenu -i -p "Action: " -theme dmenu`

conf="No
Yes"
operation_1="No"
if [ $operation ]; then
    operation_1=`echo "$conf" | rofi -dmenu -i -p "Are you sure to $operation? " -theme dmenu`
fi

if [ $operation_1 = "Yes" ]; then
    case $operation in
        shutdown )
            systemctl poweroff;;
        suspend )
            systemctl suspend;;
        reboot )
            systemctl reboot;;
        hibernate )
            systemctl hibernate;;
        logout )
            id=`loginctl | grep $(whoami) | awk -F' ' '{ print $1 }'`
            loginctl kill-session $id
            ;;
        lock )
            i3lock -c "#1d2021";;
    esac
fi
