# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="jonathan"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in ~/.oh-my-zsh/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.

bindkey -v  # activate zsh vim mode
plugins=(
    git
    vi-mode
)

if [ -f "$ZSH/oh-my-zsh.sh" ]; then
    source $ZSH/oh-my-zsh.sh
else
    echo "Oh-my-zsh not found at $ZSH/oh-my-zsh.sh"
    echo "Please install oh-my-zsh or check the path"
fi

# User configuration
# Edit line in vim with ctrl-e:
# autoload edit-command-line; zle -N edit-command-line
# bindkey '^e' edit-command-line

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.


# setting vim as EDITOR
export VISUAL=nvim
export EDITOR="$VISUAL"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

# source ~/.config/zsh/alias.zsh
source $HOME/dotfiles/zsh/alias.zsh

# pyenv init
# export PYENV_ROOT="$HOME/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"
#
# eval "$(pyenv init -)"

. "$HOME/.local/bin/env"

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/:$PATH"

# Source local secrets (not tracked by git)
if [ -f ~/.zshrc.local ]; then
    source ~/.zshrc.local
fi

# ============================================
# Devcontainer Workflow Functions
# ============================================

# Start devcontainer
devc-up() {
  local workspace="${1:-.}"
  echo "Starting devcontainer for $workspace..."
  devcontainer up --workspace-folder "$workspace"
}

# Get interactive shell (with tmux)
devc-shell() {
  local workspace="${1:-.}"
  devcontainer exec --workspace-folder "$workspace" tmux new-session -A -s main
}

# Open neovim
devc-nvim() {
  local workspace="${1:-.}"
  local file="${2:-}"
  if [[ -n "$file" ]]; then
    devcontainer exec --workspace-folder "$workspace" nvim "$file"
  else
    devcontainer exec --workspace-folder "$workspace" nvim
  fi
}

# Open yazi
devc-yazi() {
  local workspace="${1:-.}"
  devcontainer exec --workspace-folder "$workspace" yazi
}

# Run arbitrary command
devc-exec() {
  local workspace="${1:-.}"
  shift
  devcontainer exec --workspace-folder "$workspace" "$@"
}

# All-in-one: start and connect
devc() {
  local workspace="${1:-.}"
  devc-up "$workspace"
  devc-shell "$workspace"
}

# Stop container
devc-down() {
  local workspace="${1:-.}"
  local abs_workspace=$(cd "$workspace" && pwd)
  local container_id=$(docker ps -q --filter "label=devcontainer.local_folder=$abs_workspace")
  if [[ -n "$container_id" ]]; then
    docker stop "$container_id"
    echo "Container stopped"
  else
    echo "No running container found for $abs_workspace"
  fi
}

# Aliases for common commands in container
alias daws="devc-exec . aws"
alias dgh="devc-exec . gh"
alias dtofu="devc-exec . tofu"
alias dclaude="devc-exec . claude"
alias duv="devc-exec . uv"
